# Generated by Django 6.0 on 2025-12-22 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="cover_letters/")),
                ("original_filename", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettre de motivation",
                "verbose_name_plural": "Lettres de motivation",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="cvs/")),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Termine"),
                            ("failed", "Echec"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("extracted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("summary", "Resume / Accroche"),
                            ("experience", "Experience professionnelle"),
                            ("education", "Formation"),
                            ("skill_hard", "Competence technique"),
                            ("skill_soft", "Soft skill"),
                            ("language", "Langue"),
                            ("certification", "Certification"),
                            ("interest", "Centre d'interet"),
                            ("other", "Autre"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by_user", models.BooleanField(default=False)),
                (
                    "source_cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_lines",
                        to="accounts.cv",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne extraite",
                "verbose_name_plural": "Lignes extraites",
                "ordering": ["content_type", "order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "content_type"],
                        name="accounts_ex_user_id_73cd25_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_ex_user_id_3aafea_idx",
                    ),
                    models.Index(fields=["source_cv"], name="accounts_ex_source__6710e9_idx"),
                ],
            },
        ),
    ]
