# Generated by Django 6.0 on 2025-12-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_cv_coverletter_extractedline"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="task_id",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
