# Generated by Django 6.0 on 2025-12-23 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_add_task_id_to_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("free", "Gratuit"),
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("headhunter", "Head Hunter"),
                    ("enterprise", "Entreprise"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserLLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, help_text="Enable custom LLM configuration"),
                ),
                (
                    "llm_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="Custom LLM API endpoint (e.g., https://api.openai.com/v1)",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        help_text="Model name (e.g., gpt-4o, claude-3-sonnet)",
                        max_length=100,
                    ),
                ),
                (
                    "llm_api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key (stored encrypted in production)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration LLM utilisateur",
                "verbose_name_plural": "Configurations LLM utilisateurs",
            },
        ),
    ]
