# Generated by Django 6.0 on 2025-12-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_add_subscription_and_llm_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedline",
            name="dates",
            field=models.CharField(
                blank=True,
                help_text="Date range (e.g., '2020-2023', 'Jan 2020 - Present')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractedline",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of responsibilities/achievements or field of study",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractedline",
            name="entity",
            field=models.CharField(
                blank=True,
                help_text="Company/school/organization name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractedline",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="Job title or diploma name",
                max_length=255,
                null=True,
            ),
        ),
    ]
