# Generated by Django 6.0 on 2025-12-23 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_add_photo_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contract_types",
            field=models.JSONField(
                blank=True, default=list, help_text="List of desired contract types (cdi, cdd, freelance, alternance)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, help_text="City/location", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="mobility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("city", "Ville uniquement"),
                    ("region", "Region"),
                    ("france", "France entiere"),
                    ("europe", "Europe"),
                    ("international", "International"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="personal_notes",
            field=models.TextField(blank=True, help_text="Personal notes or additional information"),
        ),
        migrations.AddField(
            model_name="user",
            name="seniority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("intern", "Stagiaire"),
                    ("apprentice", "Alternant"),
                    ("junior", "Junior (0-2 ans)"),
                    ("confirmed", "Confirme (2-5 ans)"),
                    ("senior", "Senior (5-10 ans)"),
                    ("expert", "Expert / Lead (10+ ans)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("immediate", "Immediate"),
                    ("1_month", "1 mois"),
                    ("2_months", "2 mois"),
                    ("3_months", "3 mois"),
                    ("more", "Plus de 3 mois"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="salary_max",
            field=models.IntegerField(blank=True, help_text="Maximum salary in k€ gross/year", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="salary_min",
            field=models.IntegerField(blank=True, help_text="Minimum salary in k€ gross/year", null=True),
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("portfolio", "Portfolio"),
                            ("blog", "Blog personnel"),
                            ("medium", "Medium"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien social",
                "verbose_name_plural": "Liens sociaux",
                "ordering": ["order", "link_type"],
            },
        ),
    ]
