# Generated by Django 6.0 on 2025-12-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_add_personal_data_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedline",
            name="email",
            field=models.EmailField(blank=True, help_text="Email from CV", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="extractedline",
            name="first_name",
            field=models.CharField(blank=True, help_text="First name from CV", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="extractedline",
            name="last_name",
            field=models.CharField(blank=True, help_text="Last name from CV", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="extractedline",
            name="link_type",
            field=models.CharField(
                blank=True,
                help_text="Type of social link (linkedin, github, portfolio, blog, medium, other)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractedline",
            name="location",
            field=models.CharField(blank=True, help_text="Location/city from CV", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="extractedline",
            name="phone",
            field=models.CharField(blank=True, help_text="Phone number from CV", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="extractedline",
            name="url",
            field=models.URLField(blank=True, help_text="URL of the social link", null=True),
        ),
        migrations.AlterField(
            model_name="extractedline",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("summary", "Resume / Accroche"),
                    ("experience", "Experience professionnelle"),
                    ("education", "Formation"),
                    ("skill_hard", "Competence technique"),
                    ("skill_soft", "Soft skill"),
                    ("language", "Langue"),
                    ("certification", "Certification"),
                    ("interest", "Centre d'interet"),
                    ("personal_info", "Informations personnelles"),
                    ("social_link", "Lien social"),
                    ("other", "Autre"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
