# Generated by Django 6.0 on 2025-12-23 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_add_structured_fields_to_extractedline"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Auto-generated title based on conversation content", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Terminee"), ("abandoned", "Abandonnee")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "context_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of user context at conversation start (profile, experiences, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation chat",
                "verbose_name_plural": "Conversations chat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalSuccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Short title for the success (e.g., 'Improved customer retention by 18%')",
                        max_length=255,
                    ),
                ),
                (
                    "situation",
                    models.TextField(
                        blank=True,
                        help_text="S - Context: Where, when, what was the environment, what were the stakes?",
                    ),
                ),
                (
                    "task",
                    models.TextField(blank=True, help_text="T - Task: What was YOUR specific mission/responsibility?"),
                ),
                (
                    "action",
                    models.TextField(
                        blank=True, help_text="A - Actions: What did YOU do concretely? (use 'I', not 'we')"
                    ),
                ),
                ("result", models.TextField(blank=True, help_text="R - Results: What were the measurable outcomes?")),
                (
                    "skills_demonstrated",
                    models.JSONField(default=list, help_text="List of skills demonstrated in this success"),
                ),
                ("is_draft", models.BooleanField(default=True, help_text="Whether this success is still a draft")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conversation that generated this success (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_successes",
                        to="accounts.chatconversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_successes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Succes professionnel",
                "verbose_name_plural": "Succes professionnels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Utilisateur"), ("assistant", "Assistant"), ("system", "Systeme")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminee"),
                            ("failed", "Echec"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Task ID for async processing polling",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("extracted_data", models.JSONField(default=dict, help_text="STAR elements detected in this message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="accounts.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message chat",
                "verbose_name_plural": "Messages chat",
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["conversation", "created_at"], name="accounts_ch_convers_e1a524_idx")],
            },
        ),
    ]
