# Generated by Django 6.0 on 2025-12-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_add_pitch_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_autonomy_level",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="AI autonomy level (1=Guided, 2=Assisted, 3=Collaborative, 4=Proactive, 5=Autonomous)",
            ),
        ),
    ]
