# Generated by Django 6.0 on 2025-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_add_ai_autonomy_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalsuccess",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this success is included in the candidate profile"
            ),
        ),
    ]
