# Generated by Django 6.0 on 2025-12-24 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_add_is_active_to_professionalsuccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_url", models.URLField(help_text="Original URL of the job offer", max_length=500)),
                (
                    "source_domain",
                    models.CharField(help_text="Domain name of the source (e.g., linkedin.com)", max_length=100),
                ),
                ("captured_at", models.DateTimeField(help_text="When the offer was captured by the extension")),
                ("title", models.CharField(max_length=300)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "contract_type",
                    models.CharField(blank=True, help_text="Contract type (CDI, CDD, etc.)", max_length=50),
                ),
                (
                    "remote_type",
                    models.CharField(blank=True, help_text="Remote work type (onsite, hybrid, remote)", max_length=50),
                ),
                (
                    "salary",
                    models.JSONField(blank=True, help_text="Salary info: {min, max, currency, period}", null=True),
                ),
                ("skills", models.JSONField(default=list, help_text="List of skills mentioned in the offer")),
                (
                    "match_score",
                    models.FloatField(blank=True, help_text="Match score from matching service (0-1)", null=True),
                ),
                ("matched_at", models.DateTimeField(blank=True, help_text="When the match was computed", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("viewed", "Vue"),
                            ("saved", "Sauvegardee"),
                            ("applied", "Candidature envoyee"),
                            ("rejected", "Rejetee"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Candidate profile used for matching (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_offers",
                        to="accounts.candidateprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre importee",
                "verbose_name_plural": "Offres importees",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="accounts_im_user_id_786659_idx"),
                    models.Index(fields=["user", "-captured_at"], name="accounts_im_user_id_8537ad_idx"),
                    models.Index(fields=["source_domain"], name="accounts_im_source__ad69d5_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "source_url"), name="unique_offer_per_user_url")
                ],
            },
        ),
    ]
