# Generated by Django 6.0 on 2025-12-24 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_add_imported_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("custom_cv", models.TextField(blank=True, help_text="Custom CV content tailored for this offer")),
                (
                    "custom_cv_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF of the custom CV",
                        null=True,
                        upload_to=accounts.models.application_cv_path,
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, help_text="Cover letter content tailored for this offer"),
                ),
                (
                    "cover_letter_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF of the cover letter",
                        null=True,
                        upload_to=accounts.models.application_cover_letter_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("added", "Ajoutee"),
                            ("in_progress", "En cours"),
                            ("applied", "Candidature envoyee"),
                            ("interview", "Entretien prevu"),
                            ("accepted", "Acceptee"),
                            ("rejected", "Refusee"),
                        ],
                        default="added",
                        max_length=20,
                    ),
                ),
                (
                    "interview_date",
                    models.DateTimeField(blank=True, help_text="Scheduled interview date and time", null=True),
                ),
                ("notes", models.TextField(blank=True, help_text="Personal notes about this application")),
                ("history", models.JSONField(default=list, help_text="Timeline of events for this application")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Candidate profile used for this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="accounts.candidateprofile",
                    ),
                ),
                (
                    "imported_offer",
                    models.ForeignKey(
                        help_text="The imported job offer for this application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="accounts.importedoffer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="accounts_ap_user_id_1088a8_idx"),
                    models.Index(fields=["user", "-updated_at"], name="accounts_ap_user_id_4b9c24_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "imported_offer"), name="unique_application_per_user_offer")
                ],
            },
        ),
    ]
