# Generated by Django 6.0 on 2026-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_add_docx_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="userllmconfig",
            name="llm_max_tokens",
            field=models.IntegerField(default=8192, help_text="Max tokens for LLM response (2048-32768)"),
        ),
    ]
