# Generated by Django 6.0 on 2026-01-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_add_llm_max_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="userllmconfig",
            name="llm_api_mode",
            field=models.CharField(
                choices=[
                    ("openai_compatible", "OpenAI Compatible (/v1/chat/completions)"),
                    ("ollama_native", "Ollama Native (/api/chat)"),
                ],
                default="openai_compatible",
                help_text="API mode: OpenAI compatible or native Ollama",
                max_length=20,
            ),
        ),
    ]
